curated:
  COVID:
    taxa:
    - taxid: 2697049
      name: Severe acute respiratory syndrome coronavirus 2
    segments:
      Unsegmented:
        refs:
        - NC_045512.2
        seqs:
        - NC_045512.2
  LASV:
    taxa:
    - taxid: 3052310
      name: Mammarenavirus lassense
    segments:
      S:
        refs:
        - NC_004296.1
        seqs:
        - NC_004296.1
        - KM822128.1
        - GU481068.1
        - OL774861.1
        - HQ688672.1
        - FR832711.1
        - KT992425.1
        - KU961971.1
      L:
        refs:
        - NC_004297.1
        seqs:
        - NC_004297.1
        - KM822127.1
        - GU481069.1
        - OL774860.1
        - HQ688674.1
        - FR832710.1
        - KT992435.1
        - KU961972.2
  LCMV:
    taxa:
    - taxid: 3052303
      name: Mammarenavirus choriomeningitidis
    segments:
      L:
        refs:
        - NC_077806.1
        seqs:
        - NC_077806.1
        - NC_004291.1
      S:
        refs:
        - NC_077807.1
        seqs:
        - NC_077807.1
        - NC_004294.1
  JUNV:
    taxa:
    - taxid: 2169991
      name: Mammarenavirus juninense
    segments:
      L:
        refs:
        - NC_005080.1
        seqs:
        - NC_005080.1
      S:
        refs:
        - NC_005081.1
        seqs:
        - NC_005081.1
  EBOV:
    taxa:
    - taxid: 3044781
      name: Orthoebolavirus
    segments:
      Unsegmented:
        refs:
        - NC_002549.1
        seqs:
        - NC_002549.1
        - NC_039345.1
        - NC_014373.1
        - NC_014372.1
        - NC_006432.1
        - NC_004161.1
  MARV:
    taxa:
    - taxid: 3044783
      name: Orthomarburgvirus
    segments:
      Unsegmented:
        refs:
        - NC_001608.3
        seqs:
        - NC_001608.3
        - NC_024781.1
  DENV:
    taxa:
    - taxid: 3052464
      name: Orthoflavivirus denguei
    segments:
      Unsegmented:
        refs:
        - NC_001475.2
        seqs:
        - NC_001477.1
        - NC_001474.2
        - NC_001475.2
        - NC_002640.1
  ZIKA:
    taxa:
    - taxid: 3048459
      name: Orthoflavivirus zikaense
    segments:
      Unsegmented:
        refs:
        - NC_035889.1
        seqs:
        - NC_035889.1
        - NC_012532.1
  MS2:
    taxa:
    - taxid: 329852
      name: Emesvirus zinderi
    segments:
      Unsegmented:
        refs:
        - NC_001417.2
        seqs:
        - NC_001417.2
  YFV:
    taxa:
    - taxid: 11089
      name: Yellow fever virus
    segments:
      Unsegmented:
        refs:
        - NC_002031.1
        seqs:
        - NC_002031.1
  WNV:
    taxa:
    - taxid: 11082
      name: West nile virus
    segments:
      Unsegmented:
        refs:
        - NC_009942.1
        seqs:
        - NC_009942.1
        - NC_001563.2
  HAZV:
    taxa:
    - taxid: 3052519
      name: Orthonairovirus hazaraense
    segments:
      L:
        refs:
        - NC_038709.1
        seqs:
        - NC_038709.1
      M:
        refs:
        - NC_038710.1
        seqs:
        - NC_038710.1
      S:
        refs:
        - NC_038711.1
        seqs:
        - NC_038711.1
filters:
  ARENA:
    taxa:
    - taxid: 11617
      name: Arenaviridae
  FILO:
    taxa:
    - taxid: 11266
      name: Filoviridae
  HANTA:
    taxa:
    - taxid: 1980413
      name: Hantaviridae
  NAIRO:
    taxa:
    - taxid: 1980415
      name: Nairoviridae
