LASV:
  segments:
    S:
      refs:
        - NC_004296.1
      seqs:
        - NC_004296.1
        - KM822128.1
        - GU481068.1
        - OL774861.1
        - HQ688672.1
        - FR832711.1
        - KT992425.1
        - KU961971.1
    L:
      refs:
        - NC_004297.1
      seqs:
        - NC_004297.1
        - KM822127.1
        - GU481069.1
        - OL774860.1
        - HQ688674.1
        - FR832710.1
        - KT992435.1
        - KU961972.2

MARV:
  segments:
    Unsegmented:
      refs:
        - NC_001608.3
      seqs:
        - NC_001608.3
        - NC_024781.1
