curated:
  LASV:
    taxa:
    - taxid: 3052310
      name: Mammarenavirus lassense
      organisms:
      - Mammarenavirus lassaense
      - Lassa virus Josiah
      - Lassa virus GA391
    segments:
      S:
        refs:
        - NC_004296.1
        seqs:
        - NC_004296.1
        - KM822128.1
        - GU481068.1
        - OL774861.1
        - HQ688672.1
        - FR832711.1
        - KT992425.1
        - KU961971.1
      L:
        refs:
        - NC_004297.1
        seqs:
        - NC_004297.1
        - KM822127.1
        - GU481069.1
        - OL774860.1
        - HQ688674.1
        - FR832710.1
        - KT992435.1
        - KU961972.2
  MARV:
    taxa:
    - taxid: 3044783
      name: Orthomarburgvirus
      organisms:
      - Orthomarburgvirus marburgense
      - Orthomarburgvirus
      - Marburg virus - Angola
      - Marburg virus - Uganda
      - Lake Victoria marburgvirus - Leiden
      - Lake Victoria marburgvirus - Ozolin
      - Lake Victoria marburgvirus - Ci67
      - Lake Victoria marburgvirus - DRC1999
      - Lake Victoria marburgvirus - Angola2005
      - Ravn virus - Ravn, Kenya, 1987
      - Lake Victoria marburgvirus - Popp
      - Marburg virus - Musoke, Kenya, 1980
    segments:
      Unsegmented:
        refs:
        - NC_001608.3
        seqs:
        - NC_001608.3
        - NC_024781.1
filters:
  FILO:
    taxa:
    - taxid: 11266
      name: Filoviridae
      organisms:
      - Nyctinomops bat filovirus
      - Mink stool-associated filovirus
      - Slender scalyhead filovirus
      - Scaly rockcod filovirus
      - Thamnovirus thamnaconi
      - Striavirus antennarii
      - Orthomarburgvirus marburgense
      - Orthoebolavirus zairense
      - Orthoebolavirus taiense
      - Orthoebolavirus sudanense
      - Orthoebolavirus restonense
      - Orthoebolavirus bundibugyoense
      - Orthoebolavirus bombaliense
      - Dianlovirus menglaense
      - Cuevavirus lloviuense
      - Orthomarburgvirus
      - Orthoebolavirus
      - Loetschberg virus
      - Thamnovirus percae
      - Thamnovirus kanderense
      - Tapjovirus bothropis
      - Oblavirus percae
      - Tapjovirus
      - Oblavirus
      - Kander virus
      - Tapajos virus
      - John dory filovirus FL11
      - Blue spotted goatfish filovirus FL3
      - Filoviridae sp.
      - Dianlovirus
      - Oberland virus
      - Fiwi virus
      - Thamnovirus
      - Striavirus
      - Wenling thamnaconus septentrionalis filovirus
      - Wenling frogfish filovirus
      - Bombali virus
      - Zaire ebolavirus Makona
      - Marburg virus - Angola
      - Marburg virus - Uganda
      - Bat filovirus
      - Ebola virus
      - Cuevavirus
      - Sudan ebolavirus - Nakisamata
      - Lake Victoria marburgvirus - Leiden
      - unclassified Filoviridae
      - Bundibugyo virus
      - Lake Victoria marburgvirus - Ozolin
      - Lake Victoria marburgvirus - Ci67
      - Ebola virus Yambio0403
      - Ebola virus Yambio0402
      - Ebola virus Yambio0401
      - Sudan ebolavirus - Uganda (2000)
      - Reston ebolavirus - Reston (1989)
      - Lake Victoria marburgvirus - DRC1999
      - Lake Victoria marburgvirus - Angola2005
      - Ravn virus - Ravn, Kenya, 1987
      - unclassified Ebolavirus
      - Ebola virus sp.
      - Tai Forest ebolavirus
      - Sudan ebolavirus
      - Reston ebolavirus
      - Zaire ebolavirus
      - Marburgvirus
      - Ebolavirus
      - Reston ebolavirus - Siena/Philippine-92
      - Reston ebolavirus - Reston
      - Ebola virus - Eckron (Zaire, 1976)
      - Tai Forest virus - Cote d'Ivoire, Cote d'Ivoire, 1994
      - Ebola virus - Mayinga, Zaire, 1976
      - Ebola virus - Zaire (1995)
      - Sudan ebolavirus - Maleo (1979)
      - Sudan virus - Boniface, Sudan,1976
      - Ebola virus - Gabon (1994-1997)
      - Lake Victoria marburgvirus - Popp
      - Marburg virus - Musoke, Kenya, 1980
      - Filoviridae
