curated:
  COVID:
    taxa:
    - taxid: 2697049
      name: Severe acute respiratory syndrome coronavirus 2
  LASV:
    taxa:
    - taxid: 3052310
      name: Mammarenavirus lassense
  LCMV:
    taxa:
    - taxid: 3052303
      name: Mammarenavirus choriomeningitidis
  JUNV:
    taxa:
    - taxid: 2169991
      name: Mammarenavirus juninense
  EBOV:
    taxa:
    - taxid: 3044781
      name: Orthoebolavirus
  MARV:
    taxa:
    - taxid: 3044783
      name: Orthomarburgvirus
  DENV:
    taxa:
    - taxid: 3052464
      name: Orthoflavivirus denguei
  ZIKA:
    taxa:
    - taxid: 3048459
      name: Orthoflavivirus zikaense
  MS2:
    taxa:
    - taxid: 329852
      name: Emesvirus zinderi
  YFV:
    taxa:
    - taxid: 11089
      name: Yellow fever virus
  WNV:
    taxa:
    - taxid: 11082
      name: West nile virus
  HAZV:
    taxa:
    - taxid: 3052519
      name: Orthonairovirus hazaraense
filters:
  ARENA:
    taxa:
    - taxid: 11617
      name: Arenaviridae
  FILO:
    taxa:
    - taxid: 11266
      name: Filoviridae
  HANTA:
    taxa:
    - taxid: 1980413
      name: Hantaviridae
  NAIRO:
    taxa:
    - taxid: 1980415
      name: Nairoviridae
